# Generated by Django 3.2.7 on 2021-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=-1.0, upload_to='user_profile'),
            preserve_default=False,
        ),
    ]
